# Change these first
owner: usetada # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Backoffice API
    url: $BACKOFFICE_API_URL
  - name: Bridge API
    url: $BRIDGE_API_URL
  - name: TADA Wallet API
    url: $BRIDGE_API_TADA_WALLET_URL
  - name: TADA Wallet Web API
    url: $BRIDGE_API_WALLET_WEB_URL
  - name: TADA Partner API
    url: $BRIDGE_API_TADA_PARTNER_URL
  - name: TADA Insight API
    url: $BRIDGE_API_DASHBOARD_URL
  - name: Processor API
    url: $PROCESSOR_API_UEL
  - name: Evoucher API
    url: $EGIFT_API_URL
  - name: Loyalty API
    url: $LOYALTY_API_URL
  - name: Order API
    url: $ORDER_API_URL
  - name: Inventory API
    url: $INVENTORY_API_URL
  - name: Payment API
    url: $PAYMENT_API_URL
  - name: Vendor API
    url: $VENDOR_API_URL
  - name: Msite API
    url: $BRIDGE_API_MSITE_URL
  - name: Msite
    url: $MSITE_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.usetada.com
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TADA Services Status
  introTitle: TADA Services Status page
  # introMessage: Testing
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# runner: self-hosted
user-agent: rbudiharso
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
