# Change these first
owner: usetada # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Backoffice API
    url: $BACKOFFICE_API_URL
    maxResponseTime: 5000
  - name: Bridge API
    url: $BRIDGE_API_URL
    maxResponseTime: 5000
  - name: TADA Wallet API
    url: $BRIDGE_API_TADA_WALLET_URL
    maxResponseTime: 5000
  - name: TADA Wallet Web API
    url: $BRIDGE_API_WALLET_WEB_URL
    maxResponseTime: 5000
  - name: TADA Partner API
    url: $BRIDGE_API_TADA_PARTNER_URL
    maxResponseTime: 5000
  - name: TADA Insight API
    url: $BRIDGE_API_DASHBOARD_URL
    maxResponseTime: 5000
  - name: Processor API
    url: $PROCESSOR_API_URL
    maxResponseTime: 5000
  - name: Evoucher API
    url: $EGIFT_API_URL
    maxResponseTime: 5000
  - name: Loyalty API
    url: $LOYALTY_API_URL
    maxResponseTime: 5000
  - name: Order API
    url: $ORDER_API_URL
    maxResponseTime: 5000
  - name: Inventory API
    url: $INVENTORY_API_URL
    maxResponseTime: 5000
  - name: Payment API
    url: $PAYMENT_API_URL
    maxResponseTime: 5000
  - name: Vendor API
    url: $VENDOR_API_URL
    maxResponseTime: 5000
  - name: Msite API
    url: $BRIDGE_API_MSITE_URL
    maxResponseTime: 5000
  - name: Msite
    url: $MSITE_URL
    maxResponseTime: 5000
  - name: Delivery API
    url: $OOT_API_URL
    maxResponseTime: 5000
  - name: Delivery Website
    url: $OOT_WEB_URL
    maxResponseTime: 5000
  - name: Buyfrom.io
    url: $BUYFROM_IO_URL
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usetada.com
  # baseUrl: /status-page
  name: Services Status
  introTitle: TADA Services Status Dashboard
  # introMessage: Testing
  navbar:
    - title: Status
      href: /
    - title: TADA
      href: https://www.usetada.com
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
  theme: light
  logoUrl: https://www.usetada.com/hubfs/Images/TADA-LOGO-01.png
  favicon: https://www.usetada.com/hubfs/TADA_January2019/Images/xfavicon.png.pagespeed.ic.0C3Wf7ckvY.webp

# runner: self-hosted
user-agent: rbudiharso
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
