owner: usetada
repo: status-page

sites:
  - name: TADA Insight
    url: $INSIGHT_URL
    maxResponseTime: 5000
  - name: TADA Partner Web
    url: $PARTNER_WEB_URL
    maxResponseTime: 5000
  - name: TADA Wallet Web
    url: $WALLET_WEB_URL
    maxResponseTime: 5000
  - name: Msite
    url: $MSITE_URL
    maxResponseTime: 5000
  - name: Delivery Website
    url: $OOT_WEB_URL
    maxResponseTime: 5000
  - name: Buyfrom.io
    url: $BUYFROM_IO_URL
    maxResponseTime: 5000
  - name: Backoffice API
    url: $BACKOFFICE_API_URL
    maxResponseTime: 5000
  - name: Bridge API
    url: $BRIDGE_API_URL
    maxResponseTime: 5000
  - name: TADA Wallet API
    url: $BRIDGE_API_TADA_WALLET_URL
    maxResponseTime: 5000
  - name: TADA Wallet Web API
    url: $BRIDGE_API_WALLET_WEB_URL
    maxResponseTime: 5000
  - name: TADA Partner API
    url: $BRIDGE_API_TADA_PARTNER_URL
    maxResponseTime: 5000
  - name: TADA Insight API
    url: $BRIDGE_API_DASHBOARD_URL
    maxResponseTime: 5000
  - name: Processor API
    url: $PROCESSOR_API_URL
    maxResponseTime: 5000
  - name: Evoucher API
    url: $EGIFT_API_URL
    maxResponseTime: 5000
  - name: Loyalty API
    url: $LOYALTY_API_URL
    maxResponseTime: 5000
  - name: Order API
    url: $ORDER_API_URL
    maxResponseTime: 5000
  - name: Inventory API
    url: $INVENTORY_API_URL
    maxResponseTime: 5000
  - name: Payment API
    url: $PAYMENT_API_URL
    maxResponseTime: 5000
  - name: Vendor API
    url: $VENDOR_API_URL
    maxResponseTime: 5000
  - name: Msite API
    url: $BRIDGE_API_MSITE_URL
    maxResponseTime: 5000
  - name: Delivery API
    url: $OOT_API_URL
    maxResponseTime: 5000

status-website:
  cname: status.usetada.com
  name: Services Status
  introTitle: TADA Services Status Dashboard
  navbar:
    - title: Status
      href: /
    - title: TADA
      href: https://www.usetada.com
  theme: light
  logoUrl: https://github.com/usetada/status-page/raw/6b16a09b994da741375dfa29157cab4f007e53dd/tada-new-logo-final-x-1.png
  favicon: https://www.usetada.com/hubfs/TADA_January2019/Images/xfavicon.png.pagespeed.ic.0C3Wf7ckvY.webp

user-agent: rbudiharso

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
